### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PaladinTyrion** [ryszard/goskiplist#8] opened 2015-08-18 08:19 UTC
Why didn't you wrap it in a standard way? For example, take func Insert(&& insert) in stead of func Set. And when you random a level, whether if you would consider the thread-safe？Or, will you improve that part?? Any better way to random a level?
At last, thank you too much because I've learned much from your code. Thanks again!

**Comment by ryszard** [comment] 2015-08-28 15:23
I am not sure what you mean about wrapping it in a standard way. Can you clarify?

As for thread safety: this skiplist implementation is not thread-safe, and that's by design. As a data structure implementor, you don't have enough information to decide what's the best way to ensure thread  safety, so it's better to leave it to the user.

**Comment by ryszard** [comment] 2016-02-07 13:05
closing as obsolete.

**Closed as completed by ryszard** 2016-02-07 13:05 UTC
